blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://azur.mrlar.dev/discord
    about: A place to ask general questions about the tool and/or chit chat with other Azur Lane players.
